#!/bin/sh

# echo "http://dl-cdn.alpinelinux.org/alpine/v3.12/main" > /etc/apk/repositories
# echo "http://dl-cdn.alpinelinux.org/alpine/v3.12/community" >> /etc/apk/repositories
# apk update && apk upgrade --available

# apk add -X http://dl-cdn.alpinelinux.org/alpine/v3.12/main -u alpine-keys

# # RUN echo "#http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories
# # RUN echo "#http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
# echo "http://dl-cdn.alpinelinux.org/alpine/v3.18/main" > /etc/apk/repositories
# echo "http://dl-cdn.alpinelinux.org/alpine/v3.18/community" >> /etc/apk/repositories
# apk update && apk upgrade --available

# echo "http://dl-cdn.alpinelinux.org/alpine/v3.22/main" > /etc/apk/repositories
# echo "http://dl-cdn.alpinelinux.org/alpine/v3.22/community" >> /etc/apk/repositories
# apk update && apk upgrade --available


apk add -X http://dl-cdn.alpinelinux.org/alpine/v3.12/main -u alpine-keys

for version in "v3.12" "v3.18" "v3.22"
do
    echo "http://dl-cdn.alpinelinux.org/alpine/${version}/main" > /etc/apk/repositories
    echo "http://dl-cdn.alpinelinux.org/alpine/${version}/community" >> /etc/apk/repositories
    apk update && apk upgrade --available
done

apk add php